### ISSUE TITLE
Cache invalidation manual  

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [ZeeLyn/Dapper.Extensions#10]
first of all i set cache prefix then in manual cache invalidation i need to get table name from cache prefix i can do it by set prefix for each query but is there any feature to set or get table name from prefix 

**somehing like this**: _https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor#3--setting-up-the-cache-invalidation_

**Comment by ebrahimkhodadadi** [comment]
this task just needs to save the table name in the key and provide a method to get table names and remove them from the cache is it acceptable? i want to start doing the task

**Comment by ZeeLyn** [comment]
I don't understand what the purpose of this feature is, if it's not a universal solution I'm sorry I can't accept it. If you need a custom cache key you can implement the ICacheKeyBuilder interface.
```csharp
 services.AddDapperCachingInRedis<MyCustomCacheKeyProvider>(new RedisConfiguration
 {
  
 });
```
