### ISSUE TITLE
Default cache key generation doesn't seem to work with DynamicParameters

### ISSUE THREAD

**Issue by PseudoConsulting** [ZeeLyn/Dapper.Extensions#16]
Using Dapper Caching for Redis but probably the same for others.

Seemed like it was ignoring the parameters if using DynamicParameters.   Returned the same value from cache even though parameters were different.

Looked at source and came up with this c# test.
     var sql="*some sql*;
      var p1 = new DynamicParameters();
       var p2 = new DynamicParameters();
            
        p1.Add("Test1","test1");
        p2.Add("Test1","test2");
        
        var cb = new DefaultCacheKeyBuilder(new CacheConfiguration());
        var a = cb.Generate(sql, p1,"");
        var b = cb.Generate(sql, p2,"");

Generates the same cache key.   Doesn't append the values of the actual parameters.  I get this as the string:

RemoveUnused=True&ParameterNames=System.Linq.Enumerable+SelectEnumerableIterator`2[System.Collections.Generic.KeyValuePair`2[System.String,Dapper.DynamicParameters+ParamInfo],System.String]&

I uploaded a screen cap from Jetbrains Rider.

I rolled my own that iterates the values of the dynamic parameters to get the actual values.

![2023-12-15_16-21-41](https://github.com/ZeeLyn/Dapper.Extensions/assets/143968248/ad99a3ba-0281-4dd5-be48-2b8b1f67bea5)

**Comment by PseudoConsulting** [comment]
Sorry, here's a better example.

Using DynamicParameters with same name and different values gives same cache key (incorrect),
Using "new {}" with same parameter name but different value gives different cache key (correct)

Shouldn't I be able to pass a DynamicParameters as my param?

![2023-12-15_16-21-41](https://github.com/ZeeLyn/Dapper.Extensions/assets/143968248/c0f7ba5f-4526-48e0-ac29-ef361de7dec1)

**Comment by ZeeLyn** [comment]
In the version 5.0.2 fixed, but it is recommended that you use the custom cache key:
```csharp
public async Task<IActionResult> Get()
{
	int pageindex = 1;
	var page = await Repo1.QueryPageAsync<object>("select count(*) from COMPANY;", "select * from COMPANY limit @Take OFFSET @Skip;", pageindex, 20, enableCache: true, cacheKey: $"page:{pageindex}", cacheExpire: TimeSpan.FromSeconds(100));
	return Ok(page);
}
```
