### ISSUE TITLE
sometimes the functions returns redis error in my docker server

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [ZeeLyn/Dapper.Extensions#18]
"Connect to redis-server(redis:6379 -> Unspecified/redis:6379) timeout, DEBUG: Dns.GetHostEntry(redis)=System.Net.IPHostEntry"

**Comment by ZeeLyn** [comment]
This is the [source code](https://github.com/2881099/FreeRedis/blob/22492c30cc9adfcd6af24139fd4acd120ccf953b/src/FreeRedis/Internal/DefaultRedisSocket.cs#L237-L286). You are currently using the docker name to connect. You can try to use ip to connect.
