### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by MrHencke** [ZeeLyn/Dapper.Extensions#7]
Hi, are there any plans to add an invalidate function to remove a cache entry by key?

**Comment by ZeeLyn** [comment]
1. All query methods add parameter "forceupdateCache". This parameter can ignore the cache and forced the query database,like this:
```csharp
 await Dapper.QueryAsync("select * from COMPANY where id=1 LIMIT 1 OFFSET 0;", enableCache: true, forceUpdateCache: true);
```

2. Added "RemoveCache" method,like this:
```csharp
 await Dapper.RemoveCache("key1","key2","key3");
```

**Comment by ZeeLyn** [comment]
Thank you for your feedback.
